### ISSUE TITLE
Mobile : Header | Vertical alignment of marsh logo / brgr icon

### ISSUE THREAD

**Issue by timproDev** [wheelboxer/wheelboxer#100]
oh iphone the marsh logo and hamburger icon have more white space above than below; this should be balanced

**Comment by DrewAllen88** [comment]
I'm still seeing more white space above the hamburger than below in mobile, it doesn't look centered. @wheelboxer 

![header-mobile](https://cloud.githubusercontent.com/assets/8258720/5632203/e4a9fec0-959a-11e4-8aa3-6f9b5b02b452.jpg)
