### ISSUE TITLE
Global Landing Page - Drop Down Country Selector

### ISSUE THREAD

**Issue by wheelboxer** [wheelboxer/wheelboxer#199]
Build according to previous define spec and callout unseen corner cases.

This task's parent is https://github.com/wheelboxer/wheelboxer/issues/198

![screen shot 2014-11-12 at 5 09 21 pm](https://cloud.githubusercontent.com/assets/1823722/5019592/ccfcc30c-6a8e-11e4-956f-37d5c48d6090.png)

**Comment by DrewAllen88** [comment]
This need testing in anything besides safari? I can't do that on my laptop at least.
